# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e71c0d4733184e3d12fe79b46d5cce704ab556c6ab85bb3fbf7b59e805cb6ec8063f35801116cbdb2de7813c7a5c24244ab3edf6d7d4dd74aa489a787cb66bc1

test:
  secret_key_base: 9717d64ee8b03e42d70619ed70cbf4aebc5b2e46863da2e638d1fc1f0f09e1485abfc742f634e1b9e1b3c63e4119b75b91768fdd44ebb427811919338e0d96d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
